spring.application.name=sistema-deposito

#Conexion a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/deposito_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver


# Hibernate va a crear/actualizar las tablas automaticamente segun las clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080